version: '3'

services:
  aspnet:
    build:
      context: ./jaspnet
    networks:
      - network
  
  nginx:
    build:
      context: ./jnginx
    ports:
    - "${NGINX_HTTP}:80"
    - "${NGINX_HTTPS}:443"
    depends_on:
      - aspnet
    volumes:
      - ./jnginx:/etc/nginx/preconfs
      - certbot-certs:/etc/letsencrypt
      - certbot-challenge:/var/www/certbot
    networks:
      - network
    environment:
      - ENABLE_SSL=${NGINX_SSL}

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_DATABASE: jikecemoedb
    networks:
      - network
    volumes:
      - mariadb-data:/var/lib/mysql

  certbot:
    build:
      context: ./jcertbot
      args:
        TARGET_ARCH: amd64
        QEMU_ARCH: x86_64
        CERTBOT_VERSION: 1.14.0
    volumes:
      - certbot-certs:/etc/letsencrypt
      - certbot-challenge:/var/www/certbot
  foundry:
    image: felddy/foundryvtt:release
    hostname: my_foundry_host
    volumes:
      - type: bind
        source: /home/jike/fvtt-data
        target: /data
    environment:
      - FOUNDRY_PASSWORD=${FOUNDRYVTT_PASS}
      - FOUNDRY_USERNAME=${FOUNDRYVTT_USER}
      - FOUNDRY_ADMIN_KEY:=${FOUNDRYVTT_ADMIN}
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
volumes:
  mariadb-data:
  certbot-challenge:
  certbot-certs:

networks:
  network:
    driver: bridge
