version: '3'

services:
  aspnet:
    build:
      context: ./jaspnet
    networks:
      - network
  
  nginx:
    build:
      context: ./jnginx
    ports:
    - "${NGINX_HTTP}:80"
    - "${NGINX_HTTPS}:443"
    depends_on:
      - aspnet
    volumes:
      - ./jnginx:/etc/nginx/preconfs
      - certbot-certs:/etc/letsencrypt
      - certbot-challenge:/var/www/certbot
    networks:
      - network
    environment:
      - ENABLE_SSL=${NGINX_SSL}

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: jikecemoedb
    env_file:
      - secrets.env
    networks:
      - network
    volumes:
      - mariadb-data:/var/lib/mysql

  certbot:
    image: miigotu/certbot-dns-godaddy
    command: certbot certonly
      --authenticator dns-godaddy
      --dns-godaddy-propagation-seconds 900
      --dns-godaddy-credentials /var/lib/letsencrypt/credentials.ini
      --keep-until-expiring
      --non-interactive
      --expand
      --server https://acme-v02.api.letsencrypt.org/directory
      --agree-tos
      --email "lordjike@gmail.com"
      -d jike.moe
      -d '*.jike.moe'
    volumes:
      - ./jcertbot:/var/lib/letsencrypt
      - certbot-certs:/etc/letsencrypt
    cap_drop:
      - ALL
    restart: "no"

  foundry:
    image: felddy/foundryvtt:release
    hostname: foundry.jike.moe
    volumes:
      - type: bind
        source: /home/jike/fvtt-data
        target: /data
    env_file:
      - secrets.env
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
volumes:
  mariadb-data:
  certbot-challenge:
  certbot-certs:

networks:
  network:
    driver: bridge
