version: '3'

services:
  aspnet:
    build:
      context: ./jikecemoeaspnet
    networks:
      - network
  
  nginx:
    build:
      context: ./jikecemoenginx
    ports:
    - "80:80"
    - "443:443"
    depends_on:
      - aspnet
    volumes:
      - ./jnginx/nginx.conf:/etc/nginx/nginx.conf
      - certbot-certs:/etc/letsencrypt
      - certbot-challenge:/var/www/certbot
    networks:
      - network

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: serverdoesdodatabases
      MYSQL_DATABASE: jikecemoedb
    networks:
      - network
    volumes:
      - mariadb-data:/var/lib/mysql

  certbot:
    build:
      context: ./jikecemoecertbot
      args:
        TARGET_ARCH: amd64
        QEMU_ARCH: x86_64
        CERTBOT_VERSION: 1.14.0
    volumes:
      - certbot-certs:/etc/letsencrypt
      - certbot-challenge:/var/www/certbot

volumes:
  mariadb-data:
  certbot-challenge:
  certbot-certs:

networks:
  network:
    driver: bridge
