version: '3'

services:
  aspnet:
    build:
      context: ./jaspnet
    networks:
      - network
  
  nginx:
    build:
      context: ./jnginx
    ports:
    - "$(NGINX_HTTP):80"
    - "$(NGINX_HTTPS):443"
    depends_on:
      - aspnet
    volumes:
      - ./jnginx/nginx.conf:/etc/nginx/nginx.conf
      - certbot-certs:/etc/letsencrypt
      - certbot-challenge:/var/www/certbot
    networks:
      - network
    enviroment:
      - ENABLE_SSL=$(NGINX_SSL)

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: serverdoesdodatabases
      MYSQL_DATABASE: jikecemoedb
    networks:
      - network
    volumes:
      - mariadb-data:/var/lib/mysql

  certbot:
    build:
      context: ./jcertbot
      args:
        TARGET_ARCH: amd64
        QEMU_ARCH: x86_64
        CERTBOT_VERSION: 1.14.0
    volumes:
      - certbot-certs:/etc/letsencrypt
      - certbot-challenge:/var/www/certbot

volumes:
  mariadb-data:
  certbot-challenge:
  certbot-certs:

networks:
  network:
    driver: bridge
